### PR TITLE
added support for windows

### PR DESCRIPTION
**Pull request by mark-hahn**
Works in windows.  You'll have to test in your mac of course.

### CODE REVIEW

**Comment by cliffrowley** [comment]
@mark-hahn I just published some updates to fix #1 and #2 which seems to conflict with your PR, sorry!

**Comment by mark-hahn** [comment]
I'll merge them.

**Comment by mark-hahn** [comment]
Of course it's your package so if the require bothers you I won't mind you changing it back.

**Comment by mark-hahn** [comment]
Now that I think about it, there may be no delay at load time for node built-in modules.  They may be always loaded.

**Comment by mark-hahn** [comment]
Are you going to merge this?  I installed this on a new setup and it wasn't there.

**Comment by jerone** [comment]
:shipit:

**Comment by cliffrowley** [comment]
FYI I am in the process of merging this, but there are some other API changes to deal with.  I'll push a new release asap.

**Pull request merged**
